jobream/List-of-Learning-Resources

- README.md
List of Free Python Learning Websites Added with icons for each section to look readme good!
> List of Free Python Learning Websites Added

- README.md
Frontend mentors is a great place to improve frontend skills.
> Added frontendmentors in web development

- README.md
> Add Communities To List of Learning Resources

- README.md
> Add: Books Section

- README.md
> Add Video Courses

- README.md
javascript website tutorial website link added
> javascript website tutorial

- README.md
some useful and very informative tutorial website link added in website developement section
> tutorial website

- README.md
Removed some misplaced spaces to the make the hyperlink look just right.
> Fixed rendering of hyperlinks

- README.md
Here I added [HTML Dog](https://www.htmldog.com/) to the Web Development section. Please view and see if you approve. Thank you.
> I added a link to the web development part.

- README.md
Adding Codementor under Web Development - Codementor is an educational platform where junior developers can find senior developers to improve coding skills and get help with ongoing projects in various coding languages. Its main mission is to help aspiring developers grow faster by getting guidance from seasoned developers. 
Adding DevProjects under Python - DevProjects is a community with free projects in multiple tech stacks built by the Codementor team. The website also includes solutions from other developers and discussion board for all users to participate in.
> Update README.md to add links under Web Development and Python

- README.md
Microsoft Learn Docs for learning basic Python
> Adding Python Resource Material

- README.md
added a new resource for web development - Harvard's CS50web Course
> add cs50web to web development recources

- README.md
I have added a HTML PDF that I think would really help coders. Please review my PR. Thank you 😄
> I have added a HTML PDF

- README.md
I have added a HTML website onto the README.md. Thank you. BTW, I have changed my username to AvidCoder101, so HareerSakhi is no longer a contributor.
> Update README.md by adding html.com

- README.md
I added one more resource to Web development
> added one site to the list on web development

- README.md
> fixed mentioned issues

- README.md
A quick PR : just removed HareerSakhi as a collaborator. Thanks (:
> Update README.md : removed HareerSakhi

- README.md
@CodingSpecies & @AvidCoder101 please review.
> Image Center

- README.md
> Added description to last git link

- README.md
Hey! here is minor PR see more communties was not making sense so I change it to Communities.
> See more communities to Communities

- README.md
> moved the fork to the top

- README.md
> I added the fork to communities

- README.md
Fixed a minor bug within readme.md,
@AvidCoder101 @CodingSpecies
> Fix Readme.md - Minor bug

- README.md
It's hard to find interview prep resources on Python. These resources cover all interview queries for python developers
> Added new book resources for python developers

- README.md
Added a website for learning python interactively and a book on version control. Also updated the value of the number of resources for python however I didn't make a similar change in the books section because I am not sure if this book should be included with the other books.
> Added resources for python and book

- resources/CompetitiveProgramming.md
I added some competitive programming resources
> Addition of Competitive Programming Resources

- README.md
Added new resources for Computer Networking and Git-Github. (0-100) complete for free.
> Changes in Readme.md

- README.md
Add The GitHub Repository link for learning Solidity Smart Contracts: Building DeFi DApps and Protocols for the Ethereum Blockchain
Repository consist of step by step code and video link
> Add The GitHub Repository link for learning Smart Contract

- README.md
Replaces https://github.com/jobream/List-of-Learning-Resources/pull/132 (I had accidentally deleted my fork)
I spotted some issues:
- an extra image was breaking a heading position
- typos 
- minor grammar issues
> Fix issues, grammar, and typos
